import type { Metadata } from "next";
import "../styles/globals.css";
import { fontSans } from "@/components/Fonts";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Nav/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
